# Generated by Django 2.2 on 2019-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20190614_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorited',
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
