# Generated by Django 2.2 on 2019-05-13 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190513_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(11)]),
        ),
    ]
