# Generated by Django 2.2 on 2019-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100000),
        ),
    ]
