# Generated by Django 2.2 on 2019-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190604_1253'),
        ('cart', '0006_auto_20190605_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
