# Generated by Django 2.2 on 2019-05-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190501_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special2',
            field=models.BooleanField(default=False),
        ),
    ]
