# Generated by Django 2.2 on 2019-07-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190604_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'کتگوری', 'verbose_name_plural': 'کتگوری ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
