# Generated by Django 2.2 on 2019-07-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'کامنت محصوت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
